# Linear algebra

In [5]:
# Libraries
library(tidyverse)

set.seed(42)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors


In [6]:
# Constants
pi
e <- exp(1)

# Units

rad_to_deg <- function(rad) {
    deg <- (rad * 180) / (pi)
    return(deg)
}

deg_to_rad <- function(deg) {
    rad <- (deg * pi) / (180)
    return(rad)
}


[1] 3.141593

## Product of matrices

For two vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$,

### Dot (scalar) product

The scalar product returns a scalar $\mathbf{x}'\mathbf{y} \in \mathbb{R}$.

$$
\mathbf{x}'\mathbf{y} = \mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^n x_i y_i = \left\|\mathbf{x}\right\| \left\|\mathbf{y}\right\| \cos(\theta)
$$

Where $\left\| \mathbf{x} \right\| = \left(\mathbf{x}'\mathbf{x}\right)^{\frac{1}{2}} = \sqrt{\sum_{i=1}^n x_i^2}$ (Euclidean norm).

| scalar product | angle ($\theta$) |   |
| -------------- | ---------------- | - |
| $\mathbf{x}'\mathbf{y} < 0$ | $\theta > \frac{\pi}{2} = 90^\circ$ | obtuse angle |
| $\mathbf{x}'\mathbf{y} = 0$ | $\theta = \frac{\pi}{2}$ | orthogonal |
| $\mathbf{x}'\mathbf{y} > 0$ | $\theta < \frac{\pi}{2}$ | acute angle |

Note that some fields use $\sum_{i=1}^n x_i x_i'$. This is equivalent to the formulations above.

An orthogonal projection of $\mathbf{x}$ onto the vector space of $\mathbf{y}$ is a transformation that returns the shortest distance between $\mathbf{x}$ and $\mathbf{y}$,

$$
\text{proj}_\mathbf{y}(\mathbf{x}) = \frac{\mathbf{x} \cdot \mathbf{y}}{\mathbf{y} \cdot \mathbf{y}} \mathbf{y}
$$

In [7]:
x <- c(sample.int(10, 3, replace = TRUE))
y <- c(sample.int(10, 3, replace = TRUE))

# Two ways of computing the scalar product
sum(x * y) == t(x) %*% y

[,1]
[1,] TRUE

In [8]:
scalar_product_xy <- t(x) %*% y
cosine_theta_xy <- scalar_product_xy / (norm(as.matrix(x), type="F") * norm(as.matrix(y), type="F"))
theta <- rad_to_deg(acos(cosine_theta_xy))
theta

[,1]    
[1,] 19.74273

### Matrix multiplication

The scalar product above is a special case of **matrix multiplication**. Any two matrices are said to be **conformable** iff the *number of the lead's columns equals the number of the lag's rows*. The product then inherits the lead's number of rows and the lag's number of columns. Furthermore, the result's rows are functions of the lead's rows, and its columns are functions of the lag's columns.

For $V',W\in\mathbb{R}^{n \times n} \Rightarrow V'W\in\mathbb{R}^{n \times n}$, and the $i,j$ entry is,

$$
(V'W)_{ij}=\sum_kV_{ki}W_{kj}
$$

In prose, we sum over cols. The transpose results in each element being a dot product between the columns of $V$ and $W$.

For $V,W'\in\mathbb{R}^{n \times n} \Rightarrow VW'\in\mathbb{R}^{n \times n}$, and the $i,j$ entry is,

$$
(VW')_{ij}=\sum_kV_{ik}W_{jk}
$$

In prose, we sum over rows. The transpose results in each lement being a dot product between the rows of $V$ and $W$.

Note that the process is the like in both cases. The transposes simply align the elements as required.

|        | $V' = \left[\begin{matrix} a & c \\ b & d \end{matrix}\right]$ | $W' = \left[\begin{matrix} e & g \\ f & h \end{matrix}\right]$ |
| ------ | --------- | --------- |
| $V = \left[\begin{matrix} a & b \\ c & d \end{matrix}\right]$ | | $VW'= \left[\begin{matrix} ae+bf & ag+bh \\ ce+df & cg+dh \end{matrix}\right]$ |
| $W = \left[\begin{matrix} e & f \\ g & h \end{matrix}\right]$ | $V'W = \left[\begin{matrix} ae+cg & af+ch \\ be+dg & bf+dh \end{matrix}\right]$ | |

In [9]:
# Construct matrices
m = 3

V <- matrix(sample(1:10, m^2, replace = TRUE), nrow=m, ncol=m)
W <- matrix(sample(1:10, m^2, replace = TRUE), nrow=m, ncol=m)

V

[,1] [,2] [,3]
[1,] 4    4     3  
[2,] 5    2    10  
[3,] 5    8     1

In [10]:
W

[,1] [,2] [,3]
[1,] 10   10   4   
[2,]  8    8   6   
[3,]  6    4   2

In [11]:
# V'W
t(V) %*% W

[,1] [,2] [,3]
[1,] 110  100  56  
[2,] 104   88  44  
[3,] 116  114  74

In [12]:
# VW'
V %*% t(W)

[,1] [,2] [,3]
[1,]  92   82  46  
[2,] 110  116  58  
[3,] 134  110  64