# Linear algebra

In [12]:
# Libraries
import math
import numpy as np
import random

np.random.seed(42)

In [13]:
# Constants
e = math.e
pi = math.pi

# Units

    # math.radians(); np.deg2rad()
def rad_to_deg(rad):
    deg = (rad * 180) / pi
    return deg

    # math.degrees()
def deg_to_rad(deg):
    rad = (deg * pi) / 180
    return rad

## Product of matrices

For two vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$,

### Dot (scalar) product

The scalar product returns a scalar $\mathbf{x}'\mathbf{y} \in \mathbb{R}$.

$$
\mathbf{x}'\mathbf{y} = \mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^n x_i y_i = \left\|\mathbf{x}\right\| \left\|\mathbf{y}\right\| \cos(\theta)
$$

Where $\left\| \mathbf{x} \right\| = \left(\mathbf{x}'\mathbf{x}\right)^{\frac{1}{2}} = \sqrt{\sum_{i=1}^n x_i^2}$ (Euclidean norm).

| scalar product | angle ($\theta$) |   |
| -------------- | ---------------- | - |
| $\mathbf{x}'\mathbf{y} < 0$ | $\theta > \frac{\pi}{2} = 90^\circ$ | obtuse angle |
| $\mathbf{x}'\mathbf{y} = 0$ | $\theta = \frac{\pi}{2}$ | orthogonal |
| $\mathbf{x}'\mathbf{y} > 0$ | $\theta < \frac{\pi}{2}$ | acute angle |

Note that some fields use $\sum_{i=1}^n x_i x_i'$. This is equivalent to the formulations above.

An orthogonal projection of $\mathbf{x}$ onto the vector space of $\mathbf{y}$ is a transformation that returns the shortest distance between $\mathbf{x}$ and $\mathbf{y}$,

$$
\text{proj}_\mathbf{y}(\mathbf{x}) = \frac{\mathbf{x} \cdot \mathbf{y}}{\mathbf{y} \cdot \mathbf{y}} \mathbf{y}
$$

In [14]:
x = np.array(np.random.randint(1,10,3))
y = np.array(np.random.randint(1,10,3))

# Two ways of computing the scalar product
x @ y == np.dot(x,y)

np.True_

In [15]:
# Compute the angle
scalar_product_xy = np.dot(x, y)
cosine_theta_xy = scalar_product_xy / (np.linalg.norm(x) * np.linalg.norm(y))
theta = np.degrees(np.arccos(cosine_theta_xy))
theta

np.float64(32.77681207140163)

### Matrix multiplication

The scalar product above is a special case of **matrix multiplication**. Any two matrices are said to be **conformable** iff the *number of the lead's columns equals the number of the lag's rows*. The product then inherits the lead's number of rows and the lag's number of columns. Furthermore, the result's rows are functions of the lead's rows, and its columns are functions of the lag's columns.

For $V',W\in\mathbb{R}^{n \times n} \Rightarrow V'W\in\mathbb{R}^{n \times n}$, and the $i,j$ entry is,

$$
(V'W)_{ij}=\sum_kV_{ki}W_{kj}
$$

In prose, we sum over cols. The transpose results in each element being a dot product between the columns of $V$ and $W$.

For $V,W'\in\mathbb{R}^{n \times n} \Rightarrow VW'\in\mathbb{R}^{n \times n}$, and the $i,j$ entry is,

$$
(VW')_{ij}=\sum_kV_{ik}W_{jk}
$$

In prose, we sum over rows. The transpose results in each lement being a dot product between the rows of $V$ and $W$.

Note that the process is the like in both cases. The transposes simply align the elements as required.

|        | $V' = \left[\begin{matrix} a & c \\ b & d \end{matrix}\right]$ | $W' = \left[\begin{matrix} e & g \\ f & h \end{matrix}\right]$ |
| ------ | --------- | --------- |
| $V = \left[\begin{matrix} a & b \\ c & d \end{matrix}\right]$ | | $VW'= \left[\begin{matrix} ae+bf & ag+bh \\ ce+df & cg+dh \end{matrix}\right]$ |
| $W = \left[\begin{matrix} e & f \\ g & h \end{matrix}\right]$ | $V'W = \left[\begin{matrix} ae+cg & af+ch \\ be+dg & bf+dh \end{matrix}\right]$ | |

In [32]:
# Construct matrices
rng = np.random.default_rng()

m = 3

V = rng.integers(11, size=(m, m), endpoint=True)
W = rng.integers(11, size=(m, m), endpoint=True)

V

array([[ 4, 10,  2],
       [ 1,  1,  9],
       [ 0,  6, 11]])

In [33]:
W

array([[11,  9,  2],
       [ 4,  7,  9],
       [ 6,  7,  8]])

In [34]:
# Check the transposition functions
V.transpose() == V.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
# V'W
V.T @ W

array([[ 48,  43,  17],
       [150, 139,  77],
       [124, 158, 173]])

In [36]:
# VW'
V @ W.transpose()

array([[138, 104, 110],
       [ 38,  92,  85],
       [ 76, 141, 130]])